package com.tci.ventas.pasaje.domain.model.entity;

// Generated 23/07/2013 06:09:34 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BusPisoPosicionObjetoId generated by hbm2java
 */
@Embeddable
public class BusPisoPosicionObjetoId implements java.io.Serializable {

	@Column(name = "id_posicion", nullable = false)
	private Long idPosicion;

	@Column(name = "id_objeto", nullable = false)
	private Long idObjeto;

	public Long getIdPosicion() {
		return this.idPosicion;
	}

	public void setIdPosicion(Long idPosicion) {
		this.idPosicion = idPosicion;
	}

	public Long getIdObjeto() {
		return this.idObjeto;
	}

	public void setIdObjeto(Long idObjeto) {
		this.idObjeto = idObjeto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BusPisoPosicionObjetoId))
			return false;
		BusPisoPosicionObjetoId castOther = (BusPisoPosicionObjetoId) other;

		return (this.getIdPosicion() == castOther.getIdPosicion())
				&& (this.getIdObjeto() == castOther.getIdObjeto());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdPosicion().intValue();
		result = 37 * result + this.getIdObjeto().intValue();
		return result;
	}

}
